name: Build and Push Docker Images

# Trigger AMD64 builds for cloud deployment compatibility

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push MCP Server
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.mcp
        push: true
        tags: deveshpandey/logintel-mcp-server:latest
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push UI
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.ui
        push: true
        tags: deveshpandey/logintel-ui:latest
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Elasticsearch
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.elasticsearch
        push: true
        tags: deveshpandey/logintel-elasticsearch:latest
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Kibana
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.kibana
        push: true
        tags: deveshpandey/logintel-kibana:latest
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max